"""
7-STEP PRO-TRADER PROMPT FRAMEWORK
Structured analysis with anti-hallucination guard.
"""

import json
from datetime import datetime, timezone, timedelta

IST = timezone(timedelta(hours=5, minutes=30))


def get_7step_system_prompt() -> str:
    return """You are a disciplined long-term pro trader. Reason in 7 steps using ONLY the
numbers given. NEVER invent any price, %, or target. If a number is missing, say "data N/A".
Reply in friendly Hinglish, max 8 lines.

STEPS:
1. Regime    : Is market Risk-On/Neutral/Risk-Off? (use VIX, FII/DII)
2. Trend     : SMA50 vs SMA200 + ADX strength
3. Momentum  : RSI level + MACD
4. Demand    : Is price near the demand zone / support?
5. Risk      : SL distance, R:R ratio
6. Conviction: Map to STRONG_BUY / BUY / HOLD / WAIT
7. Action    : Exact entry, SL, TP1/TP2 + position-sizing hint

RULES:
- Only use numbers from the INPUT dict. Do NOT fabricate data.
- Keep response concise — Hinglish trader tone.
- End with VERDICT emoji: 🟢 STRONG_BUY / 🟡 BUY / 🔴 SELL / ⚪ HOLD / ⏳ WAIT
- Mention exact prices for entry, SL, TP1, TP2.
- Risk-reward ratio is mandatory."""


def build_analysis_prompt(quant_data: dict, live_snapshot: str = "", user_query: str = "") -> str:
    """Build the user prompt with Quant Brain data injected (not generated by LLM)."""
    now = datetime.now(IST)
    date_str = now.strftime("%d %b %Y")
    time_str = now.strftime("%I:%M %p IST")

    prompt = f"""ANALYSIS INPUT (facts only — do not invent):
Symbol: {quant_data.get('symbol', 'N/A')}
Date: {date_str} | Time: {time_str}

VERDICT: {quant_data.get('verdict', 'N/A')} (confidence: {quant_data.get('confidence', 0)}%)
TREND: {quant_data.get('trend', 'N/A')} (SMA50: {quant_data.get('sma50', 'N/A')} vs SMA200: {quant_data.get('sma200', 'N/A')})
REGIME: {quant_data.get('regime', 'N/A')} | VIX: {quant_data.get('vix', 'N/A')}

INDICATORS:
- RSI(14): {quant_data.get('rsi', 'N/A')}
- ADX(14): {quant_data.get('adx', 'N/A')}
- MACD: {json.dumps(quant_data.get('macd', {}))}
- ATR(14): {quant_data.get('atr', 'N/A')}

PRICE POINTS:
- Entry: {quant_data.get('entry', 'N/A')}
- Stop Loss: {quant_data.get('sl', 'N/A')}
- Target 1: {quant_data.get('tp1', 'N/A')}
- Target 2: {quant_data.get('tp2', 'N/A')}
- R:R: {quant_data.get('rr', 'N/A')}

SUPPORT: {quant_data.get('support', 'N/A')} | RESISTANCE: {quant_data.get('resistance', 'N/A')}
FIB LEVELS: {json.dumps(quant_data.get('fib_levels', {}))}
VOLUME: {json.dumps(quant_data.get('volume_profile', {}))}

REASONS: {quant_data.get('reason', 'N/A')}
"""

    if live_snapshot:
        prompt += f"\nLIVE MARKET SNAPSHOT:\n{live_snapshot}\n"

    if user_query:
        prompt += f"\nUSER QUESTION: {user_query}\n"

    prompt += "\nProvide your 7-step analysis based ONLY on the above data."
    return prompt


def build_signals_prompt(quant_results: list) -> str:
    """Build prompt for batch signal scanning."""
    now = datetime.now(IST)
    date_str = now.strftime("%d %b %Y %I:%M %p IST")

    prompt = f"""SCAN RESULTS — {date_str}

Analyze these Quant Brain results and rank the best opportunities:

"""
    for r in quant_results:
        prompt += f"""
{r.get('symbol', 'N/A')}: {r.get('verdict', 'N/A')} ({r.get('confidence', 0)}%)
  RSI={r.get('rsi', 'N/A')} | Trend={r.get('trend', 'N/A')} | R:R={r.get('rr', 'N/A')}
  Entry={r.get('entry', 'N/A')} | SL={r.get('sl', 'N/A')} | TP1={r.get('tp1', 'N/A')}
"""

    prompt += """
Rank the top BUY/STRONG_BUY opportunities. Keep it brief — Hinglish trader tone.
For each: symbol, verdict, entry price, SL, TP1, R:R ratio."""
    return prompt


def build_portfolio_prompt(quant_results: list, portfolio_ctx: str) -> str:
    """Build prompt for portfolio analysis."""
    now = datetime.now(IST)
    date_str = now.strftime("%d %b %Y %I:%M %p IST")

    prompt = f"""PORTFOLIO ANALYSIS — {date_str}

=== PORTFOLIO DATA ===
{portfolio_ctx}

=== QUANT BRAIN ANALYSIS ===
"""
    for r in quant_results:
        prompt += f"""
{r.get('symbol', 'N/A')}: {r.get('verdict', 'N/A')} ({r.get('confidence', 0)}%)
  RSI={r.get('rsi', 'N/A')} | Trend={r.get('trend', 'N/A')} | Regime={r.get('regime', 'N/A')}
  Entry={r.get('entry', 'N/A')} | SL={r.get('sl', 'N/A')} | TP1={r.get('tp1', 'N/A')} | R:R={r.get('rr', 'N/A')}
  Reasons: {r.get('reason', 'N/A')}
"""

    prompt += """
Analyze ALL positions. For each: current status, conviction, and verdict.
Provide overall portfolio strategy and top 3 action items.
Use Pro Trader Hinglish. End with 🟢/🟡/🔴/⚪ verdict for each position."""
    return prompt
